# Name of the GitHub Actions workflow
name: Deploy

# Trigger the workflow on push and pull request events to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  # Define a job named "ci"
  ci:
    # Specify the operating system to run the job on
    runs-on: ubuntu-latest

    # Define the steps to be executed in the job
    steps:
      # Checkout the code from the repository
      - name: Checkout code from Git
        # Use the checkout action to get the code
        uses: actions/checkout@v3

      - name: Install
        # Run install
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm run test-component

      # Define a step named "Deploy"
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        # Set an environment variable with the deployment URL from secrets
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        # Run the deployment command
        run: |
          curl "$DEPLOY_URL"